Django_Project/mysite/main/urls.py
from django.urls import path

from . import views

urlpatterns =[
path("<int:id>", views.index, name="index"),
path("", views.home, name="home")
]

Django_Project/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
]

Django_Project/mysite/main/models.py
from django.db import models

# Create your models here.
class ToDoList(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Item(models.Model):
    todolist = models.ForeignKey(ToDoList, on_delete=models.CASCADE)
    text = models.CharField(max_length=300)
    complete = models.BooleanField()

    def __str__(self):
        return self.text

Django_Project/mysite/main/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import ToDoList, Item
# Create your views here.

def index(response, id):
    ls = ToDoList.objects.get(id=id)
    return render(response, "main/list.html", {"ls": ls})

def home(response):
    return render(response, "main/home.html", {})

Django_Project/mysite/main/templates/main/base.html
<html>
<head>
    <title>{% block title %}Chase's Site{% endblock %}</title>
</head>

<body>

    <div id="content", name="content"></div>
        {% block content %}
        {% endblock %}
    </div>

</body>
</html>

Django_Project/mysite/main/templates/main/home.html
{% extends 'main/base.html' %}

{% block title %}
Home
{% endblock %}

{% block content %}
<h1>Home Page</h1>
{% endblock %}

Django_Project/mysite/main/templates/main/list.html
{% extends 'main/base.html' %}

{% block title %}
View List
{% endblock %}

{% block content %}
    <h1>{{ls.name}}</h1>
    <ul>
        {% for item in ls.item_set.all %}
            {% if item.complete == True%}
                <li>{{item.text}} - COMPLETE</li>
            {% else %}
                <li>{{item.text}} - INCOMPLETE</li>
            {% endif %}
        {% endfor %}
    </ul>
{% endblock %}